//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDienNghien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.cart_product1 = new HashSet<cart_product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public string img { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public string meta { get; set; }
        public bool hide { get; set; }
        public int order { get; set; }
        public System.DateTime datebegin { get; set; }
        public int categoryid { get; set; }
        public string detail { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_product> cart_product1 { get; set; }
    }
}
